#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command "UnloadTheme"

pkill picom
pkill polybar
pkill dunst

kill $(ps aux | grep "layout.sh" | grep -v grep | awk '{print $2}')
