#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

# Symlink out to theme down.
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

# Boot picom if it exists.
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

# Load leftwm theme.
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background.
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill --randomize $SCRIPTPATH/wallpapers/
fi

# Dunst for notifications.
if [ -x "$(command -v dunst)" ]; then
  dunst -config ~/.config/dunst/dunstrc &
fi

# Boot polybar.
cd ${SCRIPTPATH}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor
do
  monitor=$monitor polybar -c config.ini main &> /tmp/polybar.log &
done

